# Generated by Django 5.0.6 on 2024-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_rename_formulas_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
