# Generated by Django 5.0.6 on 2024-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_formula_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='name_formulas',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
