# Generated by Django 5.0.6 on 2024-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_formula_name_formulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='icon_name',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
