# Generated by Django 5.0.6 on 2024-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0006_rename_formula_formula_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='style',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='name_formulas',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
